### ISSUE TITLE
showing type error between numeric float and double variable

### ISSUE THREAD

**Issue by munechika-koyo** [ktnrg45/vs-code-cython#10]
Hello,

I think this extension is really great, but the type error hovering below bothers me a little:
![Screenshot from 2023-02-07 09-06-03](https://user-images.githubusercontent.com/51052381/217115692-cefb2697-dccc-453a-bde1-e497cd113907.png)
Here, `b` is defined as a double variable.
This incompatibility might be caused by regarding numerical values as a float type in pure python.

I would appreciate it if you would take it into account.

Thank you in advance.

**Comment by ktnrg45** [comment]
Hi,

These errors are from pyright configuration in `pyrightconfig.json` or a [tool.pyright] section in `pyproject.toml`. Since this extension does not take into account most of the possible settings, this extension will now no longer use options for pyright until they can be implemented correctly. Should be fixed in 0.3.2.
